### ISSUE TITLE
IEEE Design & Test special issue on open-source silicon?

### ISSUE THREAD

**Issue by mguthaus** [kiwih/qtcore-C1#1]
I noticed that you won the eFabless competition for an AI generated design. Would you be interested in submitting something to our special issue on Open Source silicon? We have been "requiring" measurements of real silicon, but we think these ideas are cool enough that they might warrant inclusion despite just being taped-out.

You can find details here:
https://ieee-ceda.org/document/special-issue-open-source-silicon

Please send me an email: [mrg@ucsc.edu](mailto:mrg@ucsc.edu)

**Comment by kiwih** [comment]
I'll take a look and reach out, thanks!
